#!/usr/bin/env python3
"""Combine every On-Chain Operator Program file into one master document.

Run from anywhere: python3 programs/defi-program/build_master.py
Writes programs/defi-program/ON-CHAIN-OPERATOR-PROGRAM.md
"""
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
OUT = HERE / "ON-CHAIN-OPERATOR-PROGRAM.md"


def read(path):
    return (HERE / path).read_text().strip()


def module_02_with_sample():
    """Insert the sample lesson 2.2 between lessons 2.1 and 2.3."""
    mod = read("lessons/module-02-trading-on-chain.md")
    sample = read("02-sample-lesson-amm-math.md").replace("\n## ", "\n### ")
    sample = sample.replace("# Sample Lesson 2.2", "## Lesson 2.2", 1)
    mod = mod.replace("Lesson 2.2 (AMM mathematics) is in `../02-sample-lesson-amm-math.md`.\n", "")
    head, sep, tail = mod.partition("## Lesson 2.3")
    return f"{head}{sample}\n\n---\n\n{sep}{tail}"


def numbered(path, n, title):
    """Swap a source file's H1 for a numbered master-file heading."""
    return f"# {n}. {title}\n" + read(path).split("\n", 1)[1]


def lesson_files():
    """Module files in order; 2 gets the sample lesson, 8.3 comes from 03."""
    parts = []
    for f in sorted((HERE / "lessons").glob("module-*.md")):
        num = int(f.name.split("-")[1])
        if num == 9:
            parts.append(read("03-defi-strategy-mastery.md"))
        parts.append(module_02_with_sample() if num == 2 else f.read_text().strip())
    return [p.replace("](../assets/", "](assets/") for p in parts]


STAGES = [
    ("section-0-zero", "Stage 0 · Zero", [0]),
    ("section-1-foundations", "Stage 1 · Foundations", [1, 2]),
    ("section-2-practitioner", "Stage 2 · Practitioner", [3, 4, 5]),
    ("section-3-analyst", "Stage 3 · Analyst", [6, 7]),
    ("section-4-strategist", "Stage 4 · Strategist", [8, 9, 10, 11]),
    ("section-5-operator", "Stage 5 · Operator", [12, 13, 14]),
]


def module_text(num):
    f = next((HERE / "lessons").glob(f"module-{num:02d}-*.md"))
    text = module_02_with_sample() if num == 2 else f.read_text().strip()
    if num == 8:
        text += "\n\n---\n\n" + read("03-defi-strategy-mastery.md")
    return text.replace("](../assets/", "](../assets/")


def write_sections():
    """One file per stage in sections/, so the course can be reviewed or handed off in parts."""
    out = HERE / "sections"
    out.mkdir(exist_ok=True)
    for name, title, mods in STAGES:
        body = "\n\n---\n\n".join(module_text(n) for n in mods)
        body = body.replace("](assets/", "](../assets/")
        (out / f"{name}.md").write_text(
            f"# On-Chain Operator Program — {title}\n\n"
            f"*Section file generated by `build_master.py` from `lessons/` (edit the lessons, not this file). "
            f"Modules {', '.join(map(str, mods))}. Every module opens with its Mastery Starter (N.0). "
            f"Educational content only. Not financial advice.*\n\n---\n\n{body}\n")
    print(f"Wrote {len(STAGES)} section files to {out.relative_to(ROOT)}/")


def main():
    sections = [
        f"# On-Chain Operator Program — Master File\n\n"
        f"![On-Chain Operator Program](assets/brand/logo-horizontal-light.png)\n\n"
        f"*Generated {date.today().isoformat()} from `programs/defi-program/`. "
        f"Don't edit this file directly: edit the source files and run "
        f"`python3 programs/defi-program/build_master.py`.*\n\n"
        "## Contents\n"
        "1. Build status\n2. Offer, decisions & curriculum\n3. Whop setup\n"
        "4. Complete mastery map (every topic, where it's taught, at what level)\n"
        "5. Whop store listing (logo, images, copy)\n"
        "6. Operations kit (capstones, application, call script, emails, live tier, terms)\n"
        "7. Worksheets & templates\n8. Funnel changes\n9. Video scripts (VSLs, welcome, module intros) & course video plan\n"
        "10. Course content (107 lessons + 15 Mastery Starters)\n11. Skills archive\n12. Build prompt (hand this to Whop AI / Grok 4.6)",
        "# 1. Build status\n\n" + read("README.md").split("\n", 1)[1],
        numbered("01-offer-and-curriculum.md", 2, "Offer, decisions & curriculum"),
        numbered("05-whop-setup.md", 3, "Whop setup"),
        numbered("09-mastery-map.md", 4, "Complete mastery map"),
        numbered("06-whop-store-listing.md", 5, "Whop store listing"),
        numbered("07-program-operations.md", 6, "Operations kit"),
        numbered("08-worksheets.md", 7, "Worksheets & templates"),
        numbered("04-funnel-changes.md", 8, "Funnel changes (draft, not applied)"),
        *([numbered("video/SCRIPTS.md", 9, "Video scripts")] if (HERE / "video/SCRIPTS.md").exists() else []),
        *([numbered("10-video-production-plan.md", "9b", "Course video production plan")] if (HERE / "10-video-production-plan.md").exists() else []),
        "# 10. Course content\n\nAll 107 lessons and 15 Mastery Starters in curriculum order. "
        "Lesson 8.3 (strategy mastery) follows Module 8.",
        *lesson_files(),
        "# 11. Skills archive\n\n" + (ROOT / "README.md").read_text().split("\n", 1)[1].strip(),
        read("BUILD-PROMPT.md").replace("# Build Prompt", "# 12. Build Prompt", 1),
    ]
    OUT.write_text("\n\n---\n\n".join(sections) + "\n")
    write_sections()
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
