// Video scripts: the single source of truth for narration, captions and
// visuals. build_video.js renders them; it also writes ../video/SCRIPTS.md.
//
// Scene types: title, statement, strike, image, bullets, pillars, compare,
// steps, stats, quiz, logo, cta. `vo` is spoken (abbreviations spelled for
// the voice, "[[pause 3]]" for a timed pause); `cap` is the written caption.
// Reveals and highlights sync to the sentence that mentions each item.
// Rules: no income or return claims, no urgency tricks, keys never requested.

const VIDEOS = [
  {
    id: 'vsl-main',
    title: 'VSL: main (sales page & store listing)',
    size: [1920, 1080], chrome: 'minimal', music: true, speed: 0.98, seed: 5,
    thumbnail: { title: 'From zero to your own on-chain bank', subtitle: 'On-Chain Operator Program' },
    use: 'Whop store listing video, sales page hero, application page.',
    scenes: [
      { type: 'strike', big: '12% APY', after: 'What am I being paid to risk?',
        vo: 'Most people enter DeFi through a number. Twelve percent A.P.Y. Operators start with a different question. What am I being paid to risk?',
        cap: 'Most people enter DeFi through a number. 12% APY. Operators start with a different question. What am I being paid to risk?' },
      { type: 'statement', lines: ['And how do I get out?'], sub: "If you can't explain the exit, you don't understand the position yet.",
        vo: "And how do I get out? Because if you can't explain the exit, you don't understand the position yet." },
      { type: 'bullets', title: 'Why most people get hurt in DeFi', check: false,
        items: ['Setup mistakes that can’t be undone', 'Yields nobody can explain', 'Borrowing with no buffer', 'No plan for the way out'],
        vo: "Here's why most people get hurt. Setup mistakes that can't be undone: the wrong network, a leaked seed phrase, one bad approval. Yields nobody can explain, until the subsidy stops. Borrowing with no buffer, so one sharp move liquidates them. And no plan for the way out." },
      { type: 'statement', kicker: 'On-chain', lines: ["There's no help desk."], sub: 'No chargebacks. No margin calls. No one to phone. The only protection is the process you follow before you act.',
        vo: "On-chain, there's no help desk. No chargebacks. No margin calls. No one to phone. The only protection you have is the process you follow before you act." },
      { type: 'logo', tagline: 'From zero to your own on-chain bank.',
        vo: "That process is what the On-Chain Operator Program teaches. It takes you from zero, never having owned crypto, to running your capital with the discipline of your own on-chain bank." },
      { type: 'image', src: 'assets/store/gallery-01-path-to-mastery.png', eyebrow: 'The path', wide: true,
        vo: "It's built as a path, in six stages, and you do them in order. Stage zero sets everything up safely, step by step, with a printable Day-One Setup Kit. Then foundations and safety, swaps and liquidity. Then lending, yield and infrastructure risk.",
        cap: "It's built as a path, in six stages, and you do them in order. Stage 0 sets everything up safely, step by step, with a printable Day-1 Setup Kit. Then foundations and safety, swaps and liquidity. Then lending, yield and infrastructure risk." },
      { type: 'image', src: 'assets/store/gallery-05-research-loop.png', eyebrow: 'Stage 3 · Analyst', wide: true,
        vo: "In stage three, you learn to research any protocol with a six-step loop, and to read on-chain data without fooling yourself. You finish with a real due-diligence file.",
        cap: "In Stage 3, you learn to research any protocol with a 6-step loop, and to read on-chain data without fooling yourself. You finish with a real due-diligence file." },
      { type: 'image', src: 'assets/store/gallery-04-strategy-levels.png', eyebrow: 'Stage 4 · Strategist', wide: true,
        vo: "Stage four is the strategy library. Thirty playbooks in seven levels, from simple lending to fixed-rate yield, basis trades, options and hedged positions. Every one comes with its maths, its kill rules, and exactly how it loses money.",
        cap: "Stage 4 is the strategy library. 30 playbooks in 7 levels, from simple lending to fixed-rate yield, basis trades, options and hedged positions. Every one comes with its maths, its kill rules, and exactly how it loses money." },
      { type: 'image', src: 'assets/store/gallery-03-own-bank.png', eyebrow: 'Stage 5 · Operator', wide: true,
        vo: "And in stage five, you operate as your own bank. A balance sheet. Multisig custody. A credit line against your own assets. A liquidity ladder, so you're never a forced seller.",
        cap: "And in Stage 5, you operate as your own bank. A balance sheet. Multisig custody. A credit line against your own assets. A liquidity ladder, so you're never a forced seller." },
      { type: 'image', src: 'assets/charts/income-waterfall.png', eyebrow: 'The income engine', wide: true,
        vo: "Then the income engine. It measures what you expect to earn after expected losses, and it pays out less than that. Never from principal. No projections, no promises. Just honest arithmetic." },
      { type: 'compare', title: 'What makes it different',
        left: { label: 'Typical crypto course', tone: 'bad', items: ['Signals and hot tips', 'Chases the highest APY', 'Risk in the small print'] },
        right: { label: 'Operator Program', tone: 'good', items: ['A process you can repeat', 'Asks what the yield pays for', 'Risk first, with kill rules'] },
        vo: "Here's what makes it different. A typical crypto course sells signals and hot tips. This program gives you a process you can repeat. Others chase the highest A.P.Y. Here, you ask what the yield is paying you for. And where others hide risk in the small print, we put risk first, with written kill rules.",
        cap: "Here's what makes it different. A typical crypto course sells signals and hot tips. This program gives you a process you can repeat. Others chase the highest APY. Here, you ask what the yield is paying you for. And where others hide risk in the small print, we put risk first, with written kill rules." },
      { type: 'stats', stats: [['15', 'modules'], ['107', 'lessons + 15 starters'], ['30', 'strategy playbooks']], lastAccent: false,
        vo: "Fifteen modules. A hundred and seven lessons, plus a beginner starter at the top of every module. Thirty strategy playbooks.",
        cap: "15 modules. 107 lessons, plus a beginner starter at the top of every module. 30 strategy playbooks." },
      { type: 'pillars', title: "What's included",
        items: [{ icon: 'video', title: 'Narrated video lessons', text: 'Every lesson, with worked examples on screen' },
                { icon: 'chart', title: 'Calculators & worksheets', text: '20 calculators, 17 worksheet templates' },
                { icon: 'target', title: 'Capstones', text: 'Analyst and operator, with rubrics' },
                { icon: 'users', title: 'Live tier', text: 'Group sessions and reviews, on application' }],
        vo: "Every lesson comes with a narrated video lesson, with the worked examples on screen. You get calculators and worksheets for every decision. Two capstones, analyst and operator, marked against a rubric. And for those who want it, a live tier, with group sessions and reviews, on application." },
      { type: 'bullets', title: "What you won't get", check: false, items: ['Signals to copy', 'Promised or projected returns', 'Anyone asking for your keys'],
        vo: "What you won't get: signals to copy, promised or projected returns, or anyone asking for your keys. You keep custody, always." },
      { type: 'statement', kicker: 'Risk reversal', lines: ['14-day conditional refund'], sub: "Full refund within 14 days if you've completed no more than 10% of the lessons and haven't used a capstone or live session.",
        vo: "And you're covered by a fourteen-day conditional refund. If it isn't right for you, and you've completed no more than ten percent of the lessons, with no capstone or live session used, you get a full refund.",
        cap: "And you're covered by a 14-day conditional refund. If it isn't right for you, and you've completed no more than 10% of the lessons, with no capstone or live session used, you get a full refund." },
      { type: 'bullets', title: 'How to join', numbered: true, items: ['Apply: a short form', 'A 30-minute fit call', 'Your enrolment link'],
        vo: "Joining takes three steps. Apply with a short form. Then a thirty-minute fit call, where we'll tell you honestly if it isn't a fit. If it is, you'll get your enrolment link.",
        cap: "Joining takes three steps. Apply with a short form. Then a 30-minute fit call, where we'll tell you honestly if it isn't a fit. If it is, you'll get your enrolment link." },
      { type: 'cta', button: 'Apply to join', sub: 'Application-only · Course and Live tiers · Educational content only',
        vo: "The On-Chain Operator Program. From zero, to your own on-chain bank. Apply below." },
    ],
  },
  {
    id: 'vsl-short-vertical',
    title: 'VSL: 30-second vertical cut (ads, Reels, Shorts, TikTok)',
    size: [1080, 1920], chrome: 'minimal', music: true, speed: 1.0, seed: 8,
    use: 'Paid social and organic short-form. Upload as 9:16.',
    scenes: [
      { type: 'strike', big: '12% APY', after: 'Paid to risk what?',
        vo: 'Twelve percent A.P.Y. Sounds great. But what are you actually being paid to risk?',
        cap: '12% APY. Sounds great. But what are you actually being paid to risk?' },
      { type: 'statement', lines: ["On-chain, there's", 'no help desk.'], sub: 'No chargebacks. No margin calls.',
        vo: "On-chain, there's no help desk. No chargebacks. No margin calls. Just the process you follow." },
      { type: 'logo', tagline: 'From zero to your own on-chain bank.',
        vo: 'The On-Chain Operator Program takes you from zero to running your crypto with the discipline of a bank.' },
      { type: 'stats', stats: [['107', 'lessons'], ['30', 'strategy playbooks'], ['0', 'promised returns']],
        vo: 'A hundred and seven lessons. Thirty strategy playbooks. And zero promised returns. Just a process.',
        cap: '107 lessons. 30 strategy playbooks. And zero promised returns. Just a process.' },
      { type: 'cta', button: 'Apply to join', sub: 'Application-only · Not financial advice',
        vo: 'Apply to join, at the link.' },
    ],
  },
  {
    id: 'welcome',
    title: 'Welcome video (inside the program, top of Start here)',
    size: [1920, 1080], music: true, musicLevel: 0.26, tag: 'Welcome', seed: 21,
    thumbnail: { title: 'Welcome, operator', subtitle: 'Start here' },
    use: 'First thing a new member sees after purchase.',
    scenes: [
      { type: 'logo', chapter: 'Welcome', tagline: 'Welcome, operator.',
        vo: "Welcome to the On-Chain Operator Program. I'm glad you're here. In the next minute, I'll show you exactly how to get the most from it." },
      { type: 'image', chapter: 'How it works', src: 'assets/diagrams/path-to-mastery.png', eyebrow: 'Six stages, in order', wide: true,
        vo: "The program runs in six stages, and each one builds on the last. So do them in order. Stage zero gets you set up safely. Stage five has you running your own on-chain bank. Everything in between is the path from one to the other.",
        cap: "The program runs in six stages, and each one builds on the last. So do them in order. Stage 0 gets you set up safely. Stage 5 has you running your own on-chain bank. Everything in between is the path from one to the other." },
      { type: 'pillars', chapter: 'How it works', title: 'How to work every lesson',
        items: [{ icon: 'video', title: 'Watch', text: 'The video walks the idea and the numbers' },
                { icon: 'check', title: 'Do', text: 'The checklist, with a small test amount' },
                { icon: 'target', title: 'Check', text: 'Three quiz questions before moving on' }],
        vo: "Every lesson works the same way. Watch the video. It walks through the idea and the numbers on screen. Then do the checklist, for real, with a small test amount. Then check yourself with three quiz questions before you move on. The checklist is where the learning sticks." },
      { type: 'statement', chapter: 'How it works', kicker: 'New to a topic?', lines: ['Start with the', 'Mastery Starter.'], sub: 'Every module opens with one. Ten minutes from zero to ready.',
        vo: "New to a topic? Every module opens with a Mastery Starter. It takes about ten minutes, and gets you from zero to ready for that module." },
      { type: 'image', chapter: 'Your first day', src: 'assets/diagrams/setup-roadmap.png', eyebrow: 'Your first day', wide: true,
        vo: "Today, open Module Zero, and print the Day-One Setup Kit. Work through it in order. Use only an amount you can afford to lose while you learn. There's no rush.",
        cap: "Today, open Module 0, and print the Day-1 Setup Kit. Work through it in order. Use only an amount you can afford to lose while you learn. There's no rush." },
      { type: 'statement', chapter: 'The one rule', kicker: 'One rule, forever', lines: ['Never share your', 'seed phrase.'], sub: 'Nobody from this program will ever ask for it, or for your keys.',
        vo: "And one rule, forever. Never share your seed phrase. Nobody from this program will ever ask for it, or for your keys. Anyone who does is a scammer." },
      { type: 'cta', chapter: 'Begin', button: 'Open Module 0', sub: 'Educational content only · Not financial advice',
        vo: "That's it. Open Module Zero, and let's begin.", cap: "That's it. Open Module 0, and let's begin." },
    ],
  },
  {
    id: 'welcome-long',
    title: 'Welcome, long form (about 10 minutes): the full tour with worked examples',
    size: [1920, 1080], music: true, musicLevel: 0.2, tag: 'Welcome', seed: 22, maxMinutes: 12,
    thumbnail: { title: 'The full tour, with examples', subtitle: 'Start here' },
    use: 'Start here chapter: the full welcome tour. The 1-minute welcome.mp4 stays as the short version.',
    scenes: [
      { type: 'logo', chapter: 'Welcome', tagline: 'Welcome, operator.',
        vo: "Welcome to the On-Chain Operator Program. I'm really glad you're here. Over the next ten minutes, I'll walk you through the whole program, stage by stage, with real examples from the lessons. By the end, you'll know exactly what you're building, how every lesson works, and what to do today." },
      { type: 'pillars', chapter: 'Welcome', title: 'By the end of the program, you can',
        items: [{ icon: 'shield', title: 'Set up safely', text: 'Accounts, wallets and backups done right' },
                { icon: 'search', title: 'Judge any position', text: 'What it pays, what it risks, how to exit' },
                { icon: 'vault', title: 'Run your own bank', text: 'Balance sheet, custody, credit and income policy' }],
        vo: "Here's where you'll end up. First, set up safely. Your accounts, wallets and backups, done right, so a single mistake can't wipe you out. Second, judge any position. What it pays you, what it risks, and exactly how you'd get out. And third, run your own bank. A balance sheet, custody rules, a credit line, and an income policy you can actually live with." },
      { type: 'strike', chapter: 'The one question', big: '12% APY', after: 'What am I being paid to risk?',
        vo: "Everything in this program comes back to one question. Most people see a number, like twelve percent A.P.Y., and ask how much they'll make. Operators ask something different. What am I being paid to risk?",
        cap: "Everything in this program comes back to one question. Most people see a number, like 12% APY, and ask how much they'll make. Operators ask something different. What am I being paid to risk?" },
      { type: 'image', chapter: 'The one question', src: 'assets/diagrams/base-vs-emissions.png', eyebrow: 'Example: split the APY', wide: true,
        callouts: [{ x: 0.57, y: 0.43, text: '16% is emissions', at: 2 }],
        vo: "Here's that question in action. Two pools. Pool A shows twenty percent. But only four percent comes from trading fees. The other sixteen percent is new tokens being printed as rewards, and those tokens can fall in price. Pool B shows nine percent, and eight of it is real fees. The bigger number isn't the better deal. You'll learn to split every yield like this in Module Four.",
        cap: "Here's that question in action. Two pools. Pool A shows 20%. But only 4% comes from trading fees. The other 16% is new tokens being printed as rewards, and those tokens can fall in price. Pool B shows 9%, and 8% of it is real fees. The bigger number isn't the better deal. You'll learn to split every yield like this in Module 4." },
      { type: 'image', chapter: 'The path', src: 'assets/diagrams/path-to-mastery.png', eyebrow: 'Six stages, in order', wide: true,
        vo: "Now the path. The program runs in six stages, and each one builds on the last. You'll unlock each stage by passing the one before, so you never reach leverage before you've mastered safety. Let's walk through them, with an example from each.",
        cap: "Now the path. The program runs in six stages, and each one builds on the last. You'll unlock each stage by passing the one before, so you never reach leverage before you've mastered safety. Let's walk through them, with an example from each." },
      { type: 'image', chapter: 'Stage 0 · Zero', src: 'assets/diagrams/setup-roadmap.png', eyebrow: 'Stage 0 · Zero', wide: true,
        vo: "Stage zero assumes you know nothing. You'll secure your email, open and lock down an exchange account, make a first small purchase, set up a wallet, back it up, and send your first transfer. Then you'll practise on a free test network, where nothing real is at stake.",
        cap: "Stage 0 assumes you know nothing. You'll secure your email, open and lock down an exchange account, make a first small purchase, set up a wallet, back it up, and send your first transfer. Then you'll practise on a free test network, where nothing real is at stake." },
      { type: 'image', chapter: 'Stage 0 · Zero', src: 'assets/diagrams/first-buy-costs.png', eyebrow: 'Example: your first buy', wide: true,
        vo: "Here's a Stage zero example. The price on the chart is not what you pay. You lose a little to the spread, a little to the trading fee, and a little more to the network when you withdraw. So you'll compare offers by what actually lands in your wallet, not by the headline price.",
        cap: "Here's a Stage 0 example. The price on the chart is not what you pay. You lose a little to the spread, a little to the trading fee, and a little more to the network when you withdraw. So you'll compare offers by what actually lands in your wallet, not by the headline price." },
      { type: 'image', chapter: 'Stage 0 · Zero', src: 'assets/diagrams/security-baseline.png', eyebrow: 'The security baseline', wide: true,
        vo: "And Stage zero ends with a security baseline. A hardware wallet. Unique passwords with two-factor. Never sharing your keys. And bookmarking the apps you use, instead of clicking links. These four habits prevent most of the losses people suffer in crypto.",
        cap: "And Stage 0 ends with a security baseline. A hardware wallet. Unique passwords with two-factor. Never sharing your keys. And bookmarking the apps you use, instead of clicking links. These four habits prevent most of the losses people suffer in crypto." },
      { type: 'image', chapter: 'Stage 1 · Foundations', src: 'assets/diagrams/three-wallets.png', eyebrow: 'Stage 1 · Foundations', wide: true,
        vo: "Stage one is foundations. You'll learn how transactions really work, and how to protect a wallet. One idea you'll use forever is the three-wallet setup. A vault for long-term holdings that almost never signs anything. An operator wallet for active positions. And a burner, for anything new. If a burner gets drained, you lose only the burner.",
        cap: "Stage 1 is foundations. You'll learn how transactions really work, and how to protect a wallet. One idea you'll use forever is the three-wallet setup. A vault for long-term holdings that almost never signs anything. An operator wallet for active positions. And a burner, for anything new. If a burner gets drained, you lose only the burner." },
      { type: 'image', chapter: 'Stage 1 · Foundations', src: 'assets/diagrams/approval-anatomy.png', eyebrow: 'Example: read before you sign', wide: true,
        callouts: [{ x: 0.83, y: 0.45, text: 'Exact, not infinite', at: 3 }],
        vo: "Here's a Stage one example. Every time an app asks to move your tokens, it's asking for an approval. You'll read three things before you sign. Which token. Which contract can spend it. And how much. An infinite approval stays open after the trade is done. An exact one covers only this trade. You'll default to exact, and revoke what you no longer use." },
      { type: 'image', chapter: 'Stage 1 · Foundations', src: 'assets/diagrams/mev-sandwich.png', eyebrow: 'Example: a sandwich attack', wide: true,
        vo: "And here's one of the most common ways people lose money when they swap. A bot sees your trade waiting, buys just before you, and sells just after you. You get a worse price, and it keeps the difference. You'll learn how to shut that door: tight slippage, and a protected connection." },
      { type: 'image', chapter: 'Stage 1 · Foundations', src: 'assets/charts/impermanent-loss.png', eyebrow: 'Example: impermanent loss', wide: true,
        vo: "And here's a Stage one example with numbers. When you provide liquidity to a fifty-fifty pool and the price doubles, you end up about five point seven percent worse off than if you'd simply held. If it halves, it's the same five point seven percent. If it triples, it's thirteen point four. Your trading fees have to beat that line, or you'd have been better off holding.",
        cap: "And here's a Stage 1 example with numbers. When you provide liquidity to a 50/50 pool and the price doubles, you end up about 5.7% worse off than if you'd simply held. If it halves, it's the same 5.7%. If it triples, it's 13.4%. Your trading fees have to beat that line, or you'd have been better off holding." },
      { type: 'image', chapter: 'Stage 2 · Practitioner', src: 'assets/diagrams/lending-pool-flow.png', eyebrow: 'Stage 2 · Practitioner', wide: true,
        vo: "Stage two is where you become a practitioner. Lending, borrowing, yield and staking, and the infrastructure every position depends on. You'll start with how a lending pool works. Suppliers deposit, borrowers pay interest, and when a pool is nearly fully borrowed, rates jump, and lenders may not be able to withdraw." },
      { type: 'steps', chapter: 'Stage 2 · Practitioner', title: 'Example: 10 ETH, borrow $12,000',
        steps: ['Collateral = 10 × $3,000 = $30,000', 'Health factor = $30,000 × 0.80 ÷ $12,000 = 2.0', 'Liquidation price = $12,000 ÷ 8 = $1,500'],
        result: 'ETH can fall 50% before liquidation',
        vo: "And here's a worked example you'll master in lesson three point two. You deposit ten E.T.H. at three thousand dollars, so thirty thousand dollars of collateral. You borrow twelve thousand. The health factor is thirty thousand, times point eight, divided by twelve thousand. That's two. The liquidation price is twelve thousand, divided by eight. Fifteen hundred dollars. So E.T.H. can fall fifty percent before you're liquidated.",
        cap: "And here's a worked example you'll master in Lesson 3.2. You deposit 10 ETH at $3,000, so $30,000 of collateral. You borrow $12,000. The health factor is $30,000 × 0.8 ÷ $12,000. That's 2. The liquidation price is $12,000 ÷ 8. $1,500. So ETH can fall 50% before you're liquidated." },
      { type: 'image', chapter: 'Stage 2 · Practitioner', src: 'assets/charts/health-factor.png', eyebrow: 'The picture', wide: true,
        callouts: [{ x: 0.575, y: 0.431, text: 'Today: HF 2.0', at: 1 }, { x: 0.34, y: 0.631, text: '$2,000', at: 3, below: true }],
        vo: "Here's the same position as a chart. The blue line is your health factor as the price of E.T.H. moves. Borrow more, and you get the orange line instead. It hits liquidation at two thousand dollars, not fifteen hundred. More debt moves the cliff edge closer to where you're standing. You'll never borrow again without drawing this line first.",
        cap: "Here's the same position as a chart. The blue line is your health factor as the price of ETH moves. Borrow more, and you get the orange line instead. It hits liquidation at $2,000, not $1,500. More debt moves the cliff edge closer to where you're standing. You'll never borrow again without drawing this line first." },
      { type: 'image', chapter: 'Stage 3 · Analyst', src: 'assets/diagrams/research-loop.png', eyebrow: 'Stage 3 · Analyst', wide: true,
        vo: "Stage three makes you an analyst. You'll research any protocol with a six-step loop. How it works. Where its cash comes from. What it depends on. Whether it's solvent. What the evidence says. And how you'd get out. You'll finish the stage with a real due-diligence file on a real protocol." },
      { type: 'image', chapter: 'Stage 3 · Analyst', src: 'assets/diagrams/onchain-misreads.png', eyebrow: 'Example: classic misreads', wide: true,
        vo: "You'll also learn to read on-chain data without fooling yourself. Volume can be faked by trading back and forth. A thousand addresses might be one person. And total value locked counts money that's only there for the rewards. Every metric gets its caveat, and you'll learn to check it." },
      { type: 'image', chapter: 'Stage 4 · Strategist', src: 'assets/diagrams/strategy-levels.png', eyebrow: 'Stage 4 · Strategist', wide: true,
        vo: "Stage four is the strategy library. Thirty strategies in seven levels, from simple stablecoin lending, through liquidity and yield, up to fixed-rate yield, basis trades, options and hedged positions. Every one comes with its maths, its kill rules, and exactly how it loses money." },
      { type: 'image', chapter: 'Stage 4 · Strategist', src: 'assets/charts/expected-yield.png', eyebrow: 'Example: expected yield', wide: true,
        callouts: [{ x: 0.5, y: 0.72, text: '18% headline → 12% expected', at: 2 }],
        vo: "Here's how a strategist thinks about yield. Take a farm paying eighteen percent. Suppose there's a ten percent chance each year of a loss, and a loss would cost sixty percent of the money. That's an expected loss of six percent. So the expected yield is twelve, not eighteen. And the forty percent farm? After its expected loss, it barely beats the safer one, with far more risk.",
        cap: "Here's how a strategist thinks about yield. Take a farm paying 18%. Suppose there's a 10% chance each year of a loss, and a loss would cost 60% of the money. That's an expected loss of 6%. So the expected yield is 12, not 18. And the 40% farm? After its expected loss, it barely beats the safer one, with far more risk." },
      { type: 'image', chapter: 'Stage 5 · Operator', src: 'assets/diagrams/own-bank.png', eyebrow: 'Stage 5 · Operator', wide: true,
        vo: "And stage five is where you operate as your own bank. It's a method, not a licence. You'll build a balance sheet, set custody rules, open a credit line against your own assets, and ladder your liquidity, so you're never forced to sell at the worst moment." },
      { type: 'image', chapter: 'Stage 5 · Operator', src: 'assets/diagrams/custody-architecture.png', eyebrow: 'Example: custody architecture', wide: true,
        vo: "Here's the custody design you'll build. Most of your money sits in a vault that needs more than one key to move. Active positions live in an operating wallet with limits. And a small hot float handles anything new. No single lost phone, stolen key or bad signature can drain the bank." },
      { type: 'image', chapter: 'Stage 5 · Operator', src: 'assets/diagrams/liquidity-ladder.png', eyebrow: 'Example: the liquidity ladder', wide: true,
        vo: "Here's the liquidity ladder, using an example of five thousand dollars a month of spending. One month sits instantly available, in stablecoins. Five more months sit in blue-chip lending you can reach the same day. The next six to twelve months are in fixed-term positions that mature when you'll need them. Everything else can grow. You refill each rung on a schedule, so you never sell growth assets in a bad market to pay a bill.",
        cap: "Here's the liquidity ladder, using an example of $5,000 a month of spending. One month sits instantly available, in stablecoins. Five more months sit in blue-chip lending you can reach the same day. The next 6 to 12 months are in fixed-term positions that mature when you'll need them. Everything else can grow. You refill each rung on a schedule, so you never sell growth assets in a bad market to pay a bill." },
      { type: 'image', chapter: 'Stage 5 · Operator', src: 'assets/charts/income-waterfall.png', eyebrow: 'Example: the income engine', wide: true,
        vo: "And finally, the income engine. You start with the headline yield. You subtract the losses you expect. You keep part of what's left as a buffer. And only then do you decide what you can take out. You never pay out from principal. This is an illustration, not a promise. Nothing in this program promises income, and you'll learn why that honesty is what keeps a portfolio alive." },
      { type: 'pillars', chapter: 'How every lesson works', title: 'How to work every lesson',
        items: [{ icon: 'video', title: 'Watch', text: 'The video walks the idea and the numbers' },
                { icon: 'check', title: 'Do', text: 'The checklist, for real, with a small test amount' },
                { icon: 'target', title: 'Check', text: 'Three quiz questions before moving on' }],
        vo: "Now, how every lesson works. Watch the video. It walks through the idea and the numbers on screen, just like the examples you've seen. Then do the checklist, for real, with a small test amount. Then check yourself with three quiz questions before you move on. The checklist is where the learning sticks." },
      { type: 'quiz', chapter: 'How every lesson works', n: 1, of: 1, q: 'A pool pays 20%: 4% fees and 16% emissions. Which part is more durable?', a: 'The 4% from fees. Emissions are paid in a token that can fall.',
        vo: "Let's try one now, the way every lesson ends. A pool pays twenty percent. Four percent is fees, and sixteen percent is emissions. Which part is more durable? [[pause 4]] The answer: the four percent from fees. Emissions are paid in a token that can fall.",
        cap: "Let's try one now, the way every lesson ends. A pool pays 20%. 4% is fees, and 16% is emissions. Which part is more durable? The answer: the 4% from fees. Emissions are paid in a token that can fall." },
      { type: 'statement', chapter: 'How every lesson works', kicker: 'New to a topic?', lines: ['Start with the', 'Mastery Starter.'], sub: 'Every module opens with one. About ten minutes, from zero to ready.',
        vo: "And if a topic is brand new to you, every module opens with a Mastery Starter. It takes about ten minutes, and gets you from zero to ready for that module. The words you'll need, what to have in place first, and one safe first step." },
      { type: 'pillars', chapter: 'Your tools', title: 'Your tools',
        items: [{ icon: 'chart', title: 'Calculators', text: 'Health factor, impermanent loss, loops, income' },
                { icon: 'book', title: 'Worksheets', text: 'Due diligence, pre-launch, bank policies' },
                { icon: 'compass', title: 'Course Hub', text: 'Search, progress and every video in one place' },
                { icon: 'target', title: 'Capstones', text: 'Analyst and operator, with certification' }],
        vo: "You'll also have tools. Calculators for the health factor, impermanent loss, leveraged loops and income, so every number you act on is computed, not guessed. Worksheets for due diligence, pre-launch checks and your bank policies. The Course Hub, with search, your progress, and every video in one place. And two capstones, analyst and operator, that lead to certification." },
      { type: 'bullets', chapter: 'The rules', title: 'Three rules, from day one', numbered: true,
        items: ['Never share your seed phrase or keys', 'Use small test amounts while you learn', 'Write the exit down before you enter'],
        vo: "Three rules, from day one. Never share your seed phrase or keys. Nobody from this program will ever ask for them, and anyone who does is a scammer. Use small test amounts while you learn, only what you can afford to lose. And write the exit down before you enter any position." },
      { type: 'bullets', chapter: 'Your first day', title: 'Your first day', numbered: true,
        items: ['Open Module 0 and print the Day-1 Setup Kit', 'Secure your email with a password manager and 2FA', 'Work through Part A of the kit, in order', 'Take the Lesson 0.1 quiz'],
        vo: "So here's your first day. Open Module Zero, and print the Day-One Setup Kit. Secure your email with a password manager and two-factor, before anything else. Work through Part A of the kit, in order. There's no rush. Then take the lesson zero point one quiz, and you're on your way.",
        cap: "So here's your first day. Open Module 0, and print the Day-1 Setup Kit. Secure your email with a password manager and 2FA, before anything else. Work through Part A of the kit, in order. There's no rush. Then take the Lesson 0.1 quiz, and you're on your way." },
      { type: 'statement', chapter: 'Begin', kicker: 'Educational content only', lines: ['A process,', 'not a prediction.'], sub: 'Not financial advice. No results are guaranteed. You keep custody, always.',
        vo: "One last thing. This is education, not financial advice, and no results are guaranteed. What you're getting is a process. One you can explain, position by position, for as long as you invest." },
      { type: 'cta', chapter: 'Begin', button: 'Open Module 0', sub: 'Educational content only · Not financial advice',
        vo: "Welcome aboard, operator. Open Module Zero, and let's begin.", cap: "Welcome aboard, operator. Open Module 0, and let's begin." },
    ],
  },
];

// Module intro videos (one per module), generated from the curriculum so they
// never drift from it. Spoken numbers are spelled out for the voice.
const fs = require('fs');
const path = require('path');
const NUM = ['Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen'];
const clean = s => s.replace(/Mastery Starter:.*$/, 'Mastery Starter').replace(/\*|`/g, '').replace(/\s+—\s+sample lesson/i, '').replace(/,\s*full content in.*$/, '').replace(/\s*\(.*?\)\s*$/, '').trim();
const say = x => x.replace(/APY/g, 'A.P.Y.').replace(/\bLPs\b/g, 'L.P.s').replace(/\bLP\b/g, 'L.P.').replace(/\bL2s?\b/g, 'layer twos').replace(/PT\/YT/g, 'P.T. and Y.T.').replace(/\bMEV\b/g, 'M.E.V.').replace(/\bIL\b/g, 'impermanent loss').replace(/&/g, 'and');
const STAGE_OF = [0, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 4, 5, 5, 5];
const STAGE = ['Zero', 'Foundations', 'Practitioner', 'Analyst', 'Strategist', 'Operator'];
function moduleIntros() {
  const md = fs.readFileSync(path.resolve(__dirname, '../01-offer-and-curriculum.md'), 'utf8');
  const out = [];
  for (const m of md.matchAll(/### Module (\d+) — (.+?) \*\((\d+) lessons?[^)]*\)\*\n(?:Outcome: (.+)\n)?([\s\S]*?)(?=\n### |\n## |$)/g)) {
    const [, n, title, count, outcome = '', rest] = m;
    const rows = [...rest.matchAll(/^\| (\d+\.\d+) \| (.+?) \|/gm)].map(r => [r[1], clean(r[2])]).filter(r => !r[1].startsWith('Mastery Starter'));
    const lessons = rows.map(([id, t]) => `${id} ${t}`);
    const nn = String(n).padStart(2, '0'), st = STAGE_OF[+n];
    const goal = outcome.charAt(0).toUpperCase() + outcome.slice(1).replace(/\.$/, '') + '.';
    const first = rows[0] ? rows[0][1] : '';
    out.push({
      id: `module-${nn}-intro`, title: `Module ${n} intro: ${title}`, size: [1920, 1080], use: `Top of Module ${n} in the Whop course.`, group: 'modules',
      music: true, musicLevel: 0.24, tag: `Module ${n}`, seed: 30 + +n,
      thumbnail: { title, subtitle: `Module ${n}` },
      scenes: [
        { type: 'title', chapter: 'Intro', eyebrow: `Stage ${st} · ${STAGE[st]}`, num: String(n), title, src: `assets/modules/module-${nn}.png`,
          vo: `Module ${NUM[+n]}. ${say(title)}. Part of stage ${NUM[st].toLowerCase()}, ${STAGE[st]}.`, cap: `Module ${n}. ${title}. Part of Stage ${st}, ${STAGE[st]}.` },
        { type: 'statement', chapter: 'The goal', kicker: 'By the end of this module', lines: ['You will be able to…'], sub: goal,
          vo: `By the end of this module, you'll be able to ${say(outcome.replace(/\.$/, '')).replace(/^./, c => c.toLowerCase())}. That's the standard. Every lesson moves you toward it.`,
          cap: `By the end of this module, you'll be able to ${outcome.replace(/\.$/, '').replace(/^./, c => c.toLowerCase())}. That's the standard. Every lesson moves you toward it.` },
        { type: 'bullets', chapter: 'The lessons', title: `${rows.length} lessons`, items: lessons, compact: true, highlight: false,
          vo: `There are ${NUM[rows.length] ? NUM[rows.length].toLowerCase() : rows.length} lessons, starting with ${say(first)}. Each one ends with a checklist to do for real, and a three-question quiz.`,
          cap: `There are ${rows.length} lessons, starting with ${first}. Each one ends with a checklist to do for real, and a three-question quiz.` },
        { type: 'pillars', chapter: 'How to use it', title: 'How to work this module',
          items: [{ icon: 'compass', title: `Starter ${n}.0`, text: 'New to the topic? Ten minutes, zero to ready' },
                  { icon: 'book', title: 'Lessons in order', text: 'Each builds on the one before' },
                  { icon: 'check', title: 'Checklists for real', text: 'Small test amounts, every time' }],
          vo: `If the topic is new to you, start with Mastery Starter ${NUM[+n].toLowerCase()} point zero. It takes about ten minutes. Then take the lessons in order, because each one builds on the one before. And do the checklists for real, with small test amounts, every time.`,
          cap: `If the topic is new to you, start with Mastery Starter ${n}.0. It takes about ten minutes. Then take the lessons in order, because each one builds on the one before. And do the checklists for real, with small test amounts, every time.` },
        { type: 'cta', chapter: 'Begin', button: `Start lesson ${n}.0`, sub: 'Educational content only · Not financial advice',
          vo: `Let's begin, with lesson ${NUM[+n].toLowerCase()} point zero.`, cap: `Let's begin, with lesson ${n}.0.` },
      ],
    });
  }
  return out;
}
VIDEOS.push(...moduleIntros());

module.exports = { VIDEOS };
